### ISSUE TITLE
ShareGPT should record the model number

### ISSUE THREAD

**Issue by Mrw33554432** [domeccleston/sharegpt#103]
ShareGPT is a valuable source of data, but the quality of conversations are highly unstable between GPT-4 and GPT-3.5. For some experiments GPT-4 data is necessary. Is there any existing method to get GPT-4 conversations only? Or will you implement one?

**Comment by Mrw33554432** [comment]
Well if ShareGPT decide not to make those conversations public, then this feature becomes pointless. But I think you do understand how valuable the dataset you guys have - it can really push the LLM a lot forward.

**Comment by domeccleston** [comment]
@Mrw33554432 What kind of experiments are you running? If you could let me know some more info it'll help me see if we should prioritize this feature

As of recently we are recording the model number
