### ISSUE TITLE
Chrome Extension Not Working (in either Arc or Chrome browser)

### ISSUE THREAD

**Issue by seanoliver** [domeccleston/sharegpt#106]
When I click to create a ShareGPT link, a window just appears with no options confirming that I've been logged in. I'm using Arc Browser but have tried this on Chrome as well and am experiencing the same thing.

I use Google Auth to login.

![seanshot-2023-04-21-09 55 58](https://user-images.githubusercontent.com/882952/233695076-30d6bb57-6fa6-4223-b091-53b086e5066b.png)

**Comment by domeccleston** [comment]
Hey @seanoliver, do you see a 'share' button at the bottom of the screen, by the submit button?

**Comment by seanoliver** [comment]
Omg 🤦‍♂️  Yes — I do! And it works!

Thank you! Appreciate your quick reply!
