### ISSUE TITLE
More information about the project

### ISSUE THREAD

**Issue by mrinaldi97** [domeccleston/sharegpt#110]
Hello, I came across this project recently by reading about Vicuna model that was trained (also) on this conversational corpus.
Actually I had this idea of building a sharegpt-like website many months ago, but then I never realized it in practice.
So it's great that Share-GPT exists but I have some questions:
- Are the data open-source? If yes, with which license? 
- Where is the dataset saved and how it is possible to visualize it/download it?
- Why is it missing any explanation about what the project is on the webpage? ("Share your wildest ChatGPT conversations with one click." it's definitely not satisfactory in order to understand what's the project about)

I ask these questions to understand if a "rival" of share-GPT could be needed in the research community or rather (if data are opensource and dataset accessible) if share-GPT is already enough and so it's just matter of helping it grow. I work in corpora creation, and definitely a corpus of conversations is something that is very much required now, especially if these conversations are somehow categorized, with criteria such as language (I work in corpora in my native language) and subject (something that could be implemented in share-GPT in zerotime).

Thank you, don't feel offended from the questions, I like the project just I need to understand if it's something closed or open in order to work with it.

**Comment by kallewoof** [comment]
I'm afraid this data is not available to the public as is. It is only available through endpoints that the owner can change or disable at their whim. Kind of defeats the purpose of the idea, if you ask me, but perhaps the author will make the dataset public at some point.
