### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'nextElementSibling')  

### ISSUE THREAD

**Issue by plaksivayatryapka** [domeccleston/sharegpt#113]
**Behavior:**
After clicking on the share button nothing happens

**Environment:**
No other extensions installed, Kubuntu 22.04
Version 113.0.5672.63 (Official Build) snap (64-bit)

![Screenshot_20230511_122440](https://github.com/domeccleston/sharegpt/assets/20408064/4969b27b-c45b-442b-a732-97e110a75346)

P.S. Thanks for great extension!

**Comment by fbaptista** [comment]
Yes, the issue is because `document.querySelector("#__next main form textarea");` returns `null`

**Comment by fbaptista** [comment]
I found this issue to happen because the document is still loading, if you put a breakpoint on that line, it starts working

**Comment by SmartManoj** [comment]
> I found this issue to happen because the document is still loading, if you put a breakpoint on that line, it starts working

After that I called `init();` in console to get working
