### ISSUE TITLE
Unused variables which causing error

### ISSUE THREAD

**Issue by erkage** [domeccleston/sharegpt#114]
These variables are not used anywhere and the 2nd line causing the following error:
"index.js:48 Uncaught TypeError: Cannot read properties of null (reading 'nextElementSibling')"

https://github.com/domeccleston/sharegpt/blob/3ceca3aba9b62ae49546ebb0dd516ac7addf2926/extension/index.js#L46-L48

Without them the code works correctly.

**Comment by fbaptista** [comment]
same here, i just unsintsalled the plugin because of this

**Comment by jcwilk** [comment]
@erkage would you happen to have a nutshell on the quickest way to trim out that line? did you need to install your own version of the plugin? I'd be happy to fill in the details for others if you could nudge me in the right direction

**Comment by domeccleston** [comment]
@jcwilk @fbaptista Sorry about this – a fix has been merged and is pending review.

**Comment by jcwilk** [comment]
@domeccleston thanks so much! it works for me now once again, a thousand thanks for the excellent plugin :raised_hands:
