### ISSUE TITLE
Share Button Not Working

### ISSUE THREAD

**Issue by incandescentman** [domeccleston/sharegpt#119]
Hello! Share button stopped working. Google Chrome Version 113.0.5672.126 (Official Build) (arm64) on MacOS 13.3.1 (a) (22E772610a). 

I tried disabling all other Chrome extensions, logging out of OpenAI, disabling 2fa on OpenAI, logging out of ShareGPT, deleting ShareGPT extension, restarting, reinstalling ShareGPT extension and logging back in. Nothing worked.

Sometimes it says "Sharing" but nothing happens. Now it stays stuck on "Share" and does nothing. 

Any suggestions? Thank you!

**Comment by hiro-becchi** [comment]
Mine has same problem...

**Comment by abdielou** [comment]
This line seems to be the problem. Query selector returns null.

https://github.com/domeccleston/sharegpt/blob/3ceca3aba9b62ae49546ebb0dd516ac7addf2926/extension/index.js#L46

**Comment by hiro-becchi** [comment]
@abdielou  Thank you for your comment!
I am not a software engineer so I could not know what should I do.
If you can, can you explain how can I solve this problem.

**Comment by Chris-fullerton** [comment]
> This line seems to be the problem. Query selector returns null.
> 
> https://github.com/domeccleston/sharegpt/blob/3ceca3aba9b62ae49546ebb0dd516ac7addf2926/extension/index.js#L46

Seems like it's just a line of unused code https://github.com/domeccleston/sharegpt/issues/114 ?

**Comment by vincentor** [comment]
Met the same problem too, hope it be fixed soon.🥺

**Comment by dvitak** [comment]
I am having the same issue on Windows. 
Version 113.0.5672.127 (Official Build) (64-bit)

**Comment by mroswell** [comment]
One more ping, that this share button is no longer working... apparently for many of us. @domeccleston Is this issue something that you or a related team can address?
