### ISSUE TITLE
Put the database on HuggingFace

### ISSUE THREAD

**Issue by jgcb00** [domeccleston/sharegpt#126]
Hi,
Will it be possible to put the conversations to hugging face so that the open source community can use it to fine-tune open source models. I can help with that if you want.

There are already some dataset but none come close with the amount of conversation in the DB. 

Or you can enable back GET: https://sharegpt.com/api/conversations but it will be too much traffic, I think.

Regards

**Comment by oximi123** [comment]
Hi jgcb00, 
I am also currently looking for conversation dataset for fine-tuning GPT models. Can you tell me the names of some of these datasets as you've mentioned?

> Hi, Will it be possible to put the conversations to hugging face so that the open source community can use it to fine-tune open source models. I can help with that if you want.
> 
> There are already some dataset but none come close with the amount of conversation in the DB.
> 
> Or you can enable back GET: https://sharegpt.com/api/conversations but it will be too much traffic, I think.
> 
> Regards

**Comment by flozi00** [comment]
@domeccleston 👍 +1

**Comment by imoneoi** [comment]
@domeccleston +1 👍

**Comment by bizrockman** [comment]
Exactly what I thought after reading the deprecated messages today.

@domeccleston +1 👍
