### ISSUE TITLE
the code block is too narrow to show all code when I print the page into pdf in chrome

### ISSUE THREAD

**Issue by hick** [domeccleston/sharegpt#13]
I just try to print this page https://shareg.pt/AiltMBj into pdf in chrome

some parts of the code was lost: 

![image](https://user-images.githubusercontent.com/38886/205982477-864bfa1b-8fe6-4978-8773-02fc48cd3218.png)

**Comment by domeccleston** [comment]
Thanks for flagging @hick, will get this fixed. Why do you want to print the page as a PDF btw?

**Comment by hick** [comment]
> Thanks for flagging @hick, will get this fixed. Why do you want to print the page as a PDF btw?

my pleasure.  the output is useful for me,  I like reading e-books in PDF, mark some emphsises, then take my own notes in mindmap,  then archive the PDF, and review them in sometimes
