### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'textContent')

### ISSUE THREAD

**Issue by montyclt** [domeccleston/sharegpt#130]
When clicking on "Share" button, the console logs "Error generating avatar image." and process never complete.

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'textContent')
    at HTMLButtonElement.<anonymous> (index.js:85:25)
![Screenshot 2023-10-09 at 17 13 28](https://github.com/domeccleston/sharegpt/assets/9193841/bf42b671-435d-4b78-b68f-81cb31041d85)

**Comment by vincentor** [comment]
same error here

**Comment by Debanil1996** [comment]
Hi @domeccleston   Contributed  on this first time . Where is the contributing.md  .Vercel how to authorize it ?
