### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by shameer99** [domeccleston/sharegpt#19]
I would really like to be able to release at least a TestFlight of this extension for iOS. https://github.com/shameer99/sharegpt-ios

To do so I would need to get permission from the authors, as there is no license or a license allowing this needs to be added.

https://opensource.stackexchange.com/a/1721

**Comment by domeccleston** [comment]
@vicradon we've added a shortcut for iOS, does that address what you need? sharegpt.com
