### ISSUE TITLE
Change white-space styling for all chat messages

### ISSUE THREAD

**Issue by punchagan** [domeccleston/sharegpt#24]
The CSS includes `white-space: pre-wrap` style for responses. But, human inputs could also contain code, and adding this for all messages in the chat would make the shared chat look better.

Message in ChatGPT UI
![image](https://user-images.githubusercontent.com/315678/207011703-0e05a834-4515-4309-889c-be3dbd4d0fce.png)

Message in ShareGPT
![image](https://user-images.githubusercontent.com/315678/207011855-c146409b-bb7a-4c6e-afb3-cff9320d6e8b.png)

Message with additional CSS rule set in browser's debugger
![image](https://user-images.githubusercontent.com/315678/207012040-11a1c463-c8ca-4c8e-9a50-7382e1311c4a.png)

**Comment by domeccleston** [comment]
Thanks@punchagan! Can you clarify the ask? you'd like pre-wrap for chat only, not for code?

**Comment by punchagan** [comment]
https://github.com/domeccleston/sharegpt/commit/46a3e0ecd24a05e0713c8f59da0db228da70d47f added `white-space: pre-wrap` on `.response` class. I want that CSS styling added on the messages sent by the user too, not just the responses.
