### ISSUE TITLE
ShareGPT + ChatGPTHistory = <3 ! 

### ISSUE THREAD

**Issue by fire17** [domeccleston/sharegpt#27]
Hi @domeccleston Hi @benf2004 (https://github.com/benf2004/ChatGPT-History)
please mingle and have software babies
thanks!

@domeccleston you could use the auto-history feature
@benf2004 you guys could use the vercel infa for easy sharing 

should add OAuth for this, so we can sign in and sync to all our devices
so we can rerun bookmarked prompts, and potentially run macros from history threads

that would be amazing
hope you guys like this

(currently working on an extension to import an entire repo into chatgpt context)

**Comment by benf2004** [comment]
@aivct check this out!

**Comment by fire17** [comment]
Also realizing that - at the moment we can use bookedmarked marcros, we can also share them..
Similarly to Enhanced ChatGPT (which gives you cool templates), when someone has a useful prompt, they can share it with others to try out themselves. People could star or upvote. Sound like an amazing community. maybe like lexia.art but for text to text prompts

I cant wait until one of us is able to use an api to put two of these against one another.
One will train to give the best fined tuned answer, while the second is a simple discriminator that checks the outputs and scores the original prompt. Basically a loop or template or tool for improving / fine-tuning your own prompts.
I bet open/ai is already doing this haha

Or just generally when all we have left to do is, write a readme file and the project will just appear, and will improve with every test we make. feels like were not many weeks away from this being possible (even sooner)
anyone managed to run [Alice](https://github.com/greshake/Alice) or any other Terminal api ?

would love to collaborate

**Comment by domeccleston** [comment]
yo nice work @benf2004!

@fire17 we can add oauth to this easily, main blocker will be google chrome store response times to approve new perms

**Comment by fire17** [comment]
I'm glad to see you guys liking this!
@domeccleston im sharing all the time thank you!
@benf2004 i finally feel safe with knowing that my data , my prompts, are always saved

@domeccleston its really nice to hear that the challenge is mainly time awaiting perms lol
@benf2004 do you think you guys can handle saving all of the branching threads? currently i dont seem to be able to access parts of my history that were not the most recent edits.

Does anyone in this forum have the means to implement a replay of a thread ?

imagine you guys comeup with an awesome new thread, you can share it, when i open it (provider i signed in) i can hit star button that will add it to my user's history, coupled with ability to run prev threads as macros (squeezed or iterative)
this will be super powerful. I even imagine a more mature version of this, where you can enter some pattern for checking the ai's response and based on if the pattern was found/not found, you can trigger the next prompt in the macro, or refresh the answer - (kindof bruteforcing consistency)

for me the next tackle is to have it digest more of my/our data, optimally, a full repository, local or online.
my current attempt at this is to make a gist out of a repo, (that can be recovered back inside chatgpt) spiced with a bit of pre-prompting.
I put the effort to package it, you guys are welcome to try if are interested <3
```
# Install repo-gist
$ python3 -m pip install repo-gist --upgrade

# Run repo-gist (convert a repo into a gist)
$ cd ~/your_repo
$ repo-gist .
>  ::: Created Gist From Repo - file: your_repo.gist.md
> Done! To view the gist you can run:
> $ cat your-repo.gist.md 
```
if you guys solve and combine your best qualities, and I or someone else manages to feed it real production material, then all there's left to do is to add a bunch of keyboard shortcut bindings and we're almost at AI-IDE level

ps. i cant wait for gpt to just crawl through the entire github-issue space, find requests (like this issue), fork open branch, changes the repo to solve all the requests, and opens pull request. it will be like magic . honestly
this is one of the reasons im ok with my long ass detailed explanations lol, this is the data, this is the prompt

**Comment by fire17** [comment]
Sharing my progress , **was able to resume conversation with chatGPT** with the following:
```
{The following is our last conversation}
<insert exported conversation>
{let's continue back our conversation as if it never stopped}
```
![image](https://user-images.githubusercontent.com/9356048/208656236-f7a48196-1e02-4a46-abd4-37950e8d7ca8.png)

maybe it wont be that hard after all - when i mention macros (squeezed or iterative) before... this is what i mean by "squeezed"
all you got to do (if you can) is paste pre+extracted+post into the textbox, and hit Send. - it will restore the conversation (BOOM)

**Comment by fire17** [comment]
CONGRATS @benf2004 
Just saw the new update - It's AMAZING
(please please integrate with @domeccleston )
i truly love their design, and if you can add user sign in , exporting wont be to something static, rather, other people with the extension can choose to load/import into their history/bookmarks
