### ISSUE TITLE
ShareGPT loses the some css info about the code

### ISSUE THREAD

**Issue by prncoprs** [domeccleston/sharegpt#29]
The webpage generated by ShareGPT loses the information about the code, including the background and other css settings.

The original ChatGPT is as below.
<img width="706" alt="Screenshot 2022-12-22 at 04 23 55" src="https://user-images.githubusercontent.com/10610742/209101986-6d406667-1808-4126-9cc4-2a3f9df1b57c.png">
The webpage generated by ShareGPT is as below.
<img width="871" alt="Screenshot 2022-12-22 at 04 24 42" src="https://user-images.githubusercontent.com/10610742/209102163-4e9e79d5-c99c-4fb5-b5e1-047bad4e32c5.png">

After comparing these two webpage sources, I found that the generated webpage lose the css styles. 
<img width="474" alt="Screenshot 2022-12-22 at 04 28 06" src="https://user-images.githubusercontent.com/10610742/209102886-5569134f-0de4-475d-bac8-b118216b4541.png">
<img width="390" alt="Screenshot 2022-12-22 at 04 28 44" src="https://user-images.githubusercontent.com/10610742/209103047-4433733a-9ad3-4e9c-a81a-706473074255.png">

**Comment by domeccleston** [comment]
Thanks @prncoprs - this is fixed
