### ISSUE TITLE
Place to see all saved

### ISSUE THREAD

**Issue by mayurjobanputra** [domeccleston/sharegpt#3]
How do I see a list of all saved conversations? eg: sharegpt.com/user/xxxx

**Comment by steven-tey** [comment]
We don't have that feature yet since that would require auth (this is more of an MVP)! But we might add that in the future <picture data-single-emoji=":eyeses:" title=":eyeses:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..Dxvz_6og0UxWUJ-W.KCOxGRTdQT4AwMzebIYu4bS8_kGYIiuGSpqh3nzOeDsSt6yffNMNUnkiYZ5WOEXYLDlvM5yWy-9WyMIAMoLq7Tvea8O2iYoR62uCbeRap689VxXgh0h5Pg.Qi6AY2w0wJfJxZM11bNGPg" alt=":eyeses:" align="absmiddle"></picture>

**Comment by domeccleston** [comment]
Could you say more about what you'd like to be able to do @piotrski?

**Comment by piotrski** [comment]
There are several ways to solve this problem:
- The simplest would be to store the ids of shared chats locally in the user's browser locale storage. Later, when auth is developed, we could synchronise this with the db.
- Another solution would be to store the chat ids in redis for each user (using the openAPI user id or email, both are available in the API) But I'm afraid this option is not GDPR compliant.

**Comment by domeccleston** [comment]
Yeah for sure, I mean what functionality would you want to have as a user that localStorage would enable?

**Comment by piotrski** [comment]
I think the most convenient would be the ability to view all the chats I have shared from the ChatGPT nav level and/or after clicking on the extension icon in the browser. Page/popup should open with a list of links to all my shared chats.

<img width="237" alt="image" src="https://user-images.githubusercontent.com/244174/206490113-a69b1ff4-73a2-4bbd-bf3e-3826e773bc48.png">

**Comment by mayurjobanputra** [comment]
> We don't have that feature yet since that would require auth (this is more of an MVP)! But we might add that in the future <img alt=":eyeses:" width="20" height="auto" src="https://camo.githubusercontent.com/2798c65043eab646856c4ba34dab19cdb51c1ee030c234972944a7737d5eedcf/68747470733a2f2f73696e676c652d656d6f6a692e76657263656c2e6170702f6170692f656d6f6a692f65794a68624763694f694a6b615849694c434a6c626d4d694f694a424d6a553252304e4e496e302e2e4478767a5f366f6730557857554a2d572e4b434f784752546451543441774d7a6562495975346253385f6b47594969754753707168336e7a4f6544735374367966664e4d4e556e6b69595a35574f4558594c446c764d357957792d3957794d49414d6f4c713754766561384f3269596f52363275436265526170363839567858676830683550672e5169364159327730774a664a785a4d3131624e475067">

Do we really need this though?

**Comment by mayurjobanputra** [comment]
How about: if I want it saved, but for my eyes only, then I have to create an account and pay a small fee. Would that incentivize you to build a more robust solution? 

How many people have saved anyways?

**Comment by steven-tey** [comment]
Hey everyone! we just rolled that out this week: https://twitter.com/ShareGPT/status/1641589175018455040

Apologies for the late reply on this! 😅
