### ISSUE TITLE
Delete my conversation

### ISSUE THREAD

**Issue by Vectron-IITM** [domeccleston/sharegpt#32]
Hello,

I have my number and email address for my conversation with ChatGPT and I used Sharegpt to save that conversation but is now in your database and its publicly available.
is there any way I can delete that ?? so that no one will see @domeccleston

**Comment by domeccleston** [comment]
Yep, will delete this for you

**Comment by domeccleston** [comment]
Can you email me the ID of the conversation so that I can delete this for you @Vectron-IITM ? domeccleston@gmail.com

**Comment by Vectron-IITM** [comment]
Thanking you so much for the help. I have emailed you with the conversation URL @domeccleston

**Comment by Vectron-IITM** [comment]
Hello, Can you kindly delete it, please?
It's still showing explore section @domeccleston
