### ISSUE TITLE
Please add ability to make a conversation private (only accessible by direct link).

### ISSUE THREAD

**Issue by ShidaPenns** [domeccleston/sharegpt#37]
As per title. I might want to share a conversation with someone who knows me, and not want it to show up in sharegpt.com/explore/new. If this is possible I would use it much more.

If this ability is already there somewhere and I've missed it, feel free to call me an idiot.

Thanks. Great site btw. Exactly what I was needing.

**Comment by steven-tey** [comment]
It's possible to do that but for now the experience is a bit manual, unfortunately 😅 feel free to send me a DM on [Twitter](https://twitter.com/steventey) or via email to stey@vercel.com and include the conversation ID that you want to make private and I'm happy to make the change for you!

**Comment by steven-tey** [comment]
FWIW it's already possible to make a conversation private [as per the database schema](https://github.com/domeccleston/sharegpt/blob/main/sharegpt-app/prisma/schema.prisma#L76), what we need to set up is user auth to make sure the conversation is created by the user for them to be able to toggle the privacy settings of the conversation. 

Currently I'm [storing the session info of the user when the conversation is saved](https://github.com/domeccleston/sharegpt/blob/main/sharegpt-app/pages/api/conversations/index.ts#L42-L43), so if they're logged in on ShareGPT.com, the conversation should be associated with their account, but for some reason this is not working at the moment.

If anyone would like to PR, I'd really appreciate it! 🙏

**Comment by steven-tey** [comment]
Update: We removed the Explore page on ShareGPT recently so all your conversations are basically private & only accessibly by direct link! 

Closing this issue now! :)
