### ISSUE TITLE
delete a shared chat?

### ISSUE THREAD

**Issue by riflettosamente** [domeccleston/sharegpt#38]
any way to delete a shared chat? Let's just say some things get shared inadvertently since it's actually publishing live searchable to the internet, not just a unlisted link.

**Comment by steven-tey** [comment]
Hey feel free to send me a DM on [Twitter](https://twitter.com/steventey) or via email to stey@vercel.com and include the conversation ID that you'd like to be deleted + a simple way to verify that you created the conversation and I'm happy to delete it for you!

**Comment by jtoy** [comment]
Why isn't a way to delete it just added?

**Comment by steven-tey** [comment]
Update: We removed the Explore page on ShareGPT recently so all your conversations are basically private & only accessibly by direct link!

Closing this issue now! :)
