### ISSUE TITLE
delete a shared chat? 

### ISSUE THREAD

**Issue by freddofrogbasedgod** [domeccleston/sharegpt#39]
hey, there have been a few other similar issues like this, but i was wondering if there was a way that i could get a chat deleted off of sharegpt? i wrote some furaffinity type shit that i would rather keep private, or have deleted entirely. 

i would also recommend adding an 'are you sure' button to your share function hahaha

**Comment by steven-tey** [comment]
Hey feel free to send me a DM on [Twitter](https://twitter.com/steventey) or via email to stey@vercel.com and include the conversation ID that you'd like to be deleted + a simple way to verify that you created the conversation and I'm happy to delete it for you!
