### ISSUE TITLE
[BUG] - Non-functional on Linux

### ISSUE THREAD

**Issue by Xatrekak** [domeccleston/sharegpt#41]
I tested the shareGPT extension on Linux using both Chromium and official Chrome.

In both cases when clicking the share button on ChatGPT it registers the click, changes to sharing and then hangs. No further action is taken after this.

![Screenshot from 2023-02-09 12-08-44](https://user-images.githubusercontent.com/6622041/217887140-507f592b-4f47-4750-b11d-bef9418c3990.png)

![Screenshot from 2023-02-09 12-09-18](https://user-images.githubusercontent.com/6622041/217887175-797e9433-b7b2-46af-91b4-6bc607afef07.png)

Chrome console reported the follow errors:

```
index.js:54 undefined
index.js:61 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'children')
    at HTMLButtonElement.<anonymous> (index.js:61:40)
(anonymous) @ index.js:61
```

**Comment by Xatrekak** [comment]
To be meta here is the suggestion from ChatGPT:


> It looks like there is an issue with reading the properties of an undefined object in the index.js file of the extension.
> This error usually occurs when you are trying to access an object property that doesn't exist, 
> or when you are trying to access an object property before the object is defined.
> 
> Here are a few suggestions on how to resolve the issue:
> 
> 1. Check the object that is being referenced on line 54 and line 61. Make sure that it is defined and accessible in the current context.
> 3. If the object is defined and accessible, check the properties that you are trying to access. Make sure that they exist and are properly defined.
> 4. Check the compatibility of the extension with Linux. Some extensions are not compatible with all operating systems, and the issue might be related to that.
> 5. Try debugging the code by adding console.log statements to see what is going on at different stages of the code execution.
> 6. If the issue still persists, you can try reaching out to the developer of the extension or looking for alternative extensions that have better Linux compatibility.

**Comment by Ganpath-Singh-B** [comment]
Even though I got the same error message when I tested the shareGPT extension on Windows.

**Comment by benwurth** [comment]
The issue seems to be that the ChatGPT website has updated its UI and the selector string that is meant to select the "thread container" is no longer returning any results. I have submitted pull request #42 which should address this.

**Comment by Xatrekak** [comment]
> The issue seems to be that the ChatGPT website has updated its UI and the selector string that is meant to select the "thread container" is no longer returning any results. I have submitted pull request #42 which should address this.

The issue is now resolved. Thank you.
