### ISSUE TITLE
Ability to Share Bing Conversation [enhancement]

### ISSUE THREAD

**Issue by benf2004** [domeccleston/sharegpt#45]
Would it be OK if I used this in my Bing Chat History extension? I used the ShareGPT api for my ChatGPT chrome extension & I was wondering if I could use it for this new extension with the Bing Chat bot.

**Comment by domeccleston** [comment]
Hey @benf2004, are you still interested in implementing this?

**Comment by BillCampbell** [comment]
This has already been implemented. To confirm, here is an example I just shared from Bing Chat using the Bing Chat History extension: 
https://sharegpt.com/c/TUxWHqa

**Comment by benf2004** [comment]
@domeccleston 

I already did it on [Bing Chat History](https://github.com/benf2004/Bing-Chat-History)
