### ISSUE TITLE
Need my convos deleted immediately please

### ISSUE THREAD

**Issue by Roosterkobain** [domeccleston/sharegpt#49]
I emailed you about a double post of my convos thinking the copy link would only copy the content, not auto post to the world. if I was you I would fix that immediately because you have no documentation to support anything of the sort. A copy link is just that, not a post. Very deceiving and the amount of PII and proprietary information you are exposing is extremely detrimental to you. Especially with 10K plus downloads. If nothing else, provide a way for users to delete and perhaps even a popup warning. None of this has been implemented. 

I emailed you from jlk***307 at gmail. Twitter would not let me DM you for some reason but I tweeted you as well. Please remove this today and advise when done with proof of removal. I appreciate your urgent response.

**Comment by steven-tey** [comment]
Update: We removed the Explore page on ShareGPT recently so all your conversations are basically private & only accessibly by direct link! Apologies for this!

Closing this issue now! :)
