### ISSUE TITLE
avatarUrl doesn't work for the API

### ISSUE THREAD

**Issue by Kav-K** [domeccleston/sharegpt#50]
The webpage doesn't display the given avatarUrl no matter what you give it. It looks like an error with the optimizer, try 

`https://sharegpt.com/_next/image?url=https://www.google.com/images/branding/googlelogo/2x/googlelogo_light_color_272x92dp.png`

**Comment by domeccleston** [comment]
Hey @Kav-K trying to reproduce this bug - how did you arrive at the URL above?
