### ISSUE TITLE
Pagination is very slow

### ISSUE THREAD

**Issue by lodorg** [domeccleston/sharegpt#51]
Hello,

I am writing about an issue that I encountered with the "ShareGPT" repository on GitHub. When attempting to retrieve conversations by page, I noticed that as the number of pages increases, the query becomes slower, eventually leading to a timeout on the Vercel Serverless Functions. Specifically, I found it almost impossible to retrieve conversations beyond page 200.

As an example, I tried to retrieve conversations from page 1000 using the following query:
https://sharegpt.com/api/conversations?page=1000

However, the query resulted in a 504 error with the message "GATEWAY_TIMEOUT" and the code "FUNCTION_INVOCATION_TIMEOUT."

**Comment by steven-tey** [comment]
Update: We removed the Explore page on ShareGPT recently so this issue is no longer relevant – closing it now!
