### ISSUE TITLE
Request for Firefox extension

### ISSUE THREAD

**Issue by jason19970210-senao** [domeccleston/sharegpt#52]
Hello team,

thanks for the wonderful idea making world better than ever,
I am wondering to having this on my Firefox browser for sharing GPT idea !

Please help to build for Firefox users, appreciated !!

**Comment by hidao80** [comment]
@jason19970210-senao 
Hello, I have a newly created add-on for Firefox that allows you to share to ShareGPT.
It is currently in a basic working state and has not yet been registered in the store, but if you would like to try it out, please feel free to do so.
As it has not been signed and has a special installation method, please refer to the README for instructions on how to use it.

Packaged:
https://github.com/hidao80/Share-with-ShareGPT/releases/tag/v0.2

README:
https://github.com/hidao80/Share-with-ShareGPT

**Comment by kojix2** [comment]
Now Firefox extension for ShareGPT has been published and is available at [ Firefox ADD-ONS](https://addons.mozilla.org/ja/firefox/addon/share-with-sharegpt/)

[![image](https://user-images.githubusercontent.com/5798442/228713031-c7b23cf0-42e3-4bbe-a427-58b48d064ff1.png)](https://sharegpt.com/c/uYJiKxY) 

https://sharegpt.com/c/uYJiKxY

Thank you @hidao80
