### ISSUE TITLE
Sign In is broken

### ISSUE THREAD

**Issue by jtoy** [domeccleston/sharegpt#54]
an error saying try another sign in method pops up

**Comment by domeccleston** [comment]
Thanks for flagging. What's your browser?

**Comment by domeccleston** [comment]
Thansk for flagging - we're looking into this now and will have a fix shortly.

**Comment by CodeForcer** [comment]
I have the same issue, app is completely broken for me on multiple browsers

**Comment by restinplace** [comment]
Same.

**Comment by steven-tey** [comment]
We had some outages back in mid-March but they should be fixed by now – are you guys still facing this issue @restinplace @CodeForcer?

**Comment by jonathanza** [comment]
@steven-tey I'm still seeing this issue. I've cleared cookies and also signed out/in of the Google account. 

I just get redirected to this page from when clicking on the "Sign In" button on the ShareGPT home page:

`https://sharegpt.com/api/auth/signin?error=OAuthCreateAccount`

I also delete ShareGPT from my Google account using these instructions: [Manage third-party apps & services with access to your account](https://support.google.com/accounts/answer/3466521?hl=en)

After that, I attempted to sign in again. I can see ShareGPT in the list of Apps in my Google account, but am still unable to login. 

I hope this helps is debugging. If you need additional information, let me know.

**Comment by surdarla** [comment]
Having same issue here

**Comment by nguyenduchuyz190** [comment]
same issue

**Comment by mkwatson** [comment]
Same

**Comment by SophiaRP00** [comment]
I have this issue

**Comment by domeccleston** [comment]
Hey @SophiaRP00, per the readme this project is no longer maintained
