### ISSUE TITLE
Deployment: a Helm chart for k8s

### ISSUE THREAD

**Issue by gmile** [domeccleston/sharegpt#68]
First of all, thanks for an awesome project!

This is not really an issue, but more like a question - has anyone deployed this to k8s already / is there a Helm chart version of the `sharegpt` already?

Would certainly be great to have an ability to deploy `sharegpt` on our own premises, since using a public instance of `sharegpt` is not easy to justify in environments, that are super strict about security / compliance.

**Comment by domeccleston** [comment]
Hey @gmile, don't think this exists atm. Is this what you need?

- Be able to configure a share location for the Chrome Extension other than sharegpt.com
- Self-host a version of the app like sharegpt-onprem.com
- Share to that on-prem version

Any more context as to how you've been using this so far super helpful

**Comment by jjmata** [comment]
I'm interested in this as well, and have a bare-bones docker-compose.yml that I put together a few days ago.  Didn't want to waste too much time on it until the license issue is clarified (#36)

**Comment by domeccleston** [comment]
Have added a license @jjmata – hope this helps
