### ISSUE TITLE
Cannot use REST API

### ISSUE THREAD

**Issue by wwwCielwww** [domeccleston/sharegpt#69]
I have been using the API for some time now. But today when I tried to get some new ID information by requesting `https://sharegpt.com/api/conversations?type=new&page=`, the response becomes
```
{
  "error": "Method not allowed"
}
```
Does this have something to do with the broken https://sharegpt.com/explore or did I mistakenly write something? Can anyone still access the API?

**Comment by rlaengud123** [comment]
Me Too... :cry:

**Comment by zkmn73** [comment]
why this API is banned?

**Comment by zkmn73** [comment]
+1, Method not allowed

**Comment by whowillbellthecat** [comment]
The GET endpoint is disabled in b22d58dbe2b523d92675abf915aeeb8f2cc1a5be, probably due to https://twitter.com/steventey/status/1641267979399704576.

**Comment by getorca** [comment]
. That was my first thought, but seems like it was down for a few days before the articles came out. while why do you think we want the api back, not fair google get's the data and we don't, lol/
