### ISSUE TITLE
Option to save chats as PNG/PDF

### ISSUE THREAD

**Issue by AnonGitCat** [domeccleston/sharegpt#7]
Would be nice to have alternate ways to save the chats like as a PNG or PDF. It helps with sharing on the OpenAI discord since they block urls

**Comment by domeccleston** [comment]
Interesting, thanks for the feedback @AnonGitCat. Would you be looking for a single large PNG or multiple?

**Comment by hick** [comment]
> Interesting, thanks for the feedback @AnonGitCat. Would you be looking for a single large PNG or multiple?

I think @AnonGitCat want some way just like printing the page into pdf in chrome, In fact I just have a try and found some proplem, and has this issue:  https://github.com/domeccleston/sharegpt/issues/13
