### ISSUE TITLE
feature request: Enable GET API, or add a compele list in the repo

### ISSUE THREAD

**Issue by gaocegege** [domeccleston/sharegpt#70]
https://github.com/lm-sys/FastChat#data

FastChat uses ShareGPT API to get conversation data. We disabled the GET API in https://github.com/domeccleston/sharegpt/commit/b22d58dbe2b523d92675abf915aeeb8f2cc1a5be

Could we provide a complete JSON list or enable the get API again?

I'd appreciate it.

**Comment by nwhitehead** [comment]
It's probably a good idea to update the README with the status of the GET API whichever way this is resolved.

**Comment by gaocegege** [comment]
> It's probably a good idea to update the README with the status of the GET API whichever way this is resolved.

Yeah, I think so.

**Comment by domeccleston** [comment]
This is documented. Closing as duplicate of https://github.com/domeccleston/sharegpt/issues/71
