### ISSUE TITLE
sharegpt is DEAD?

### ISSUE THREAD

**Issue by Kreijstal** [domeccleston/sharegpt#73]
No way to browse anything?
What happened.
Are there alternatives? 
Some other fork?

**Comment by domeccleston** [comment]
Hey @Kreijstal, we've removed the explore page for the moment due to privacy concerns. What were you looking to do here?

**Comment by Kreijstal** [comment]
> Hey @Kreijstal, we've removed the explore page for the moment due to privacy concerns. What were you looking to do here?

share my directory of my chats to everyone obviously, I submitted them to be added to the directory, and then woops, I can't even find my own chats anymore, sad.

**Comment by PestToast** [comment]
> What were you looking to do here?

The same thing google did with Bard. Now there are two major players in the LLM space and average people are being artificially gatekept from useful datasets.

**Comment by timatom** [comment]
@PestToast

While I can't say how similar the datasets are, GPT4all appears to have an extended training set under an Apache license. From what I can tell, it looks like it contains some prompts from GPT-3 (maybe GPT-3-Turbo). You may just have to preprocess it using a similar approach mentioned under their technical report.

GPT4ALL: https://github.com/nomic-ai/gpt4all
Technical report: https://s3.amazonaws.com/static.nomic.ai/gpt4all/2023_GPT4All_Technical_Report.pdf
GPT4ALL extended training dataset: https://huggingface.co/datasets/nomic-ai/gpt4all_prompt_generations_with_p3

**Comment by Kreijstal** [comment]
I mean what is the point of sharegpt if you can't share your thing to the world, I don't want my shares to be gatekeeped, are there any shareGPT alternatives that don't gatekeep?

**Comment by timatom** [comment]
@Kreijstal,

I think you can still share your GPT conversations to the world with ShareGPT. I think the concern is for those who may not have chosen to share their conversations publicly.

You could scrape the conversation that are being shared publicly, e.g., twitter, LinkedIn, etc. That is probably a more ethical alternative considering it's being publicly shared.

**Comment by steven-tey** [comment]
@Kreijstal we just released saved conversations tab the other day, you can use that to save your conversations: https://twitter.com/ShareGPT/status/1641589175018455040

**Comment by dactylo** [comment]
For the record, not working for me.

I'm logged in to ShareGPT when I'm sharing. I get redirected to sharegpt.com and I get the shortened url, but no saved charts appear under my Dashboard.
