### ISSUE TITLE
Make sure that "Allow JavaScript from Apple Events" is enabled

### ISSUE THREAD

**Issue by dactylo** [domeccleston/sharegpt#76]
Trying from macOS 13.3:

Make sure that "Allow JavaScript from Apple Events" is enabled in the Develop menu in Safari.

But it already is enabled.

**Comment by domeccleston** [comment]
@dactylo What browser are you using? Are you using the Chrome extension in Safari?

**Comment by dactylo** [comment]
Thanks for taking a look.

I stated the browser and OS. This is using the Shortcut from the Share Sheet.

<img width="512" alt="Screenshot 2023-04-04 at 7 12 40 AM" src="https://user-images.githubusercontent.com/188462/229822089-5ee6faa7-c598-4dee-843a-7885917017f8.png">
<img width="375" alt="Screenshot 2023-04-04 at 7 12 47 AM" src="https://user-images.githubusercontent.com/188462/229822134-27780106-3618-454b-96cf-1c11d47f7196.png">
<img width="1312" alt="Screenshot 2023-04-04 at 7 12 58 AM" src="https://user-images.githubusercontent.com/188462/229822159-9f67c721-bc49-4f20-a802-a797f87c1ef0.png">
<img width="466" alt="Screenshot 2023-04-04 at 7 14 56 AM" src="https://user-images.githubusercontent.com/188462/229822183-76257760-9c50-4874-9d50-c9764ada39ce.png">

**Comment by jordancurve** [comment]
I have the same issue with 13.3.1. Using share menu from Safari > Shortcuts > ShareGPT. Same error message as OP.
