### ISSUE TITLE
Missing share button?

### ISSUE THREAD

**Issue by ccheney** [domeccleston/sharegpt#83]
I no longer have the share button in the chat gpt UI. Uninstalled/reinstalled the extension / restarted Chrome, and logged into the extension w/ oauth

**Comment by domeccleston** [comment]
Sorry to hear that @ccheney . Could you send a screenshot? I've just tried to reproduce this by uninstalling and reinstalling the extension but was not able to.

**Comment by domeccleston** [comment]
@ccheney If you open chrome developer tools (right click > view source) and navigate to the 'sources' tab and select 'content scripts', do you see sharegpt appear?
![Uploading Screenshot 2023-04-05 at 16.53.28.png…]()

**Comment by ccheney** [comment]
Ok, looks like the button is rendered into the markup so maybe a styling problem

<img width="673" alt="Screenshot 2023-04-05 at 10 50 17 AM" src="https://user-images.githubusercontent.com/302437/230137146-b876f847-3d6b-4685-9dd4-e35c76df1d61.png">

**Comment by ccheney** [comment]
```
.dark.gdpr-settings, .flex.cookie, .py-3.rgpd, .visible.scroll-to-top, .visible.cookies, .bottom-0.cookies, .btn.gotop, #share_button, #share-bottom, #share-button, #share_bottom, .text-center.cookie, .text-center.cookie-consent, .text-center.rgpd, .fixed.cookies_law, .fixed[data-cookiebar], .block.cookies {
    display: none !important;
}
```

unsure where these styles are coming from but it sets `display: none` to `#share-button`

<img width="496" alt="Screenshot 2023-04-05 at 11 02 54 AM" src="https://user-images.githubusercontent.com/302437/230138325-39895d42-9a64-43cc-95a6-128c8fb77c12.png">

**Comment by domeccleston** [comment]
@ccheney Are you using any other chrome extensions, e.g. to block cookie consent banners? This can cause the share button to be hidden

**Comment by domeccleston** [comment]
It could be from Privacy Badger or another

**Comment by ccheney** [comment]
You're right. It was uBlock origin.

Maybe update the selector for the #share-button

**Comment by domeccleston** [comment]
Will do 👍 thanks for flagging, I'll find one that's not covered by adblockers.
