### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null reading 'appendChild'

### ISSUE THREAD

**Issue by krmmzs** [domeccleston/sharegpt#9]
sharegpt does not work on my chrome.
The "Export" button is not display.
Error:
![image](https://user-images.githubusercontent.com/69446758/205824704-fd18c006-d04f-4085-a368-75183c32e738.png)
I'm not sure what other information I need to provide, please let me know.

**Comment by aakarshsingh** [comment]
It is true. On Version 108.0.5359.95 (Official Build) (64-bit) it fails.
